[webservers]
web-1.ru-central1.internal
web-2.ru-central1.internal

[elasticsearch]
elasticsearch.ru-central1.internal

[kibana]
kibana.ru-central1.internal

[zabbix]
zabbix.ru-central1.internal

[bastion]
bastion.ru-central1.internal

[all:vars]
ansible_user=ubuntu
ansible_ssh_common_args=-o ProxyJump=bastion.ru-central1.internal

[bastion:vars]
ansible_ssh_common_args=
